// <auto-generated />
using System;
using DataAccess.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(MainDBContext))]
    [Migration("20210911032912_ignoreReferencialObj")]
    partial class ignoreReferencialObj
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Addres")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("LastModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Addres = "",
                            LastModification = new DateTime(2021, 9, 10, 22, 29, 11, 738, DateTimeKind.Local).AddTicks(1261),
                            Name = "Mattel"
                        });
                });

            modelBuilder.Entity("Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AgeRestriction")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("UrlImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeRestriction = 5,
                            CompanyId = 1,
                            Description = "Racing Model 1991",
                            LastModification = new DateTime(2021, 9, 10, 22, 29, 11, 721, DateTimeKind.Local).AddTicks(4052),
                            Name = "HotWheels Model 1",
                            Price = 10.50m,
                            UrlImage = ""
                        },
                        new
                        {
                            Id = 2,
                            AgeRestriction = 3,
                            CompanyId = 1,
                            Description = "Racing Model 1991",
                            LastModification = new DateTime(2021, 9, 10, 22, 29, 11, 724, DateTimeKind.Local).AddTicks(3173),
                            Name = "HotWheels Model 2",
                            Price = 100.50m,
                            UrlImage = ""
                        },
                        new
                        {
                            Id = 3,
                            AgeRestriction = 3,
                            CompanyId = 1,
                            Description = "Racing Model 1992",
                            LastModification = new DateTime(2021, 9, 10, 22, 29, 11, 724, DateTimeKind.Local).AddTicks(3216),
                            Name = "HotWheels Model 3",
                            Price = 69.50m,
                            UrlImage = ""
                        });
                });

            modelBuilder.Entity("Models.Product", b =>
                {
                    b.HasOne("Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });
#pragma warning restore 612, 618
        }
    }
}
